name: Update Recipe List

on:
  push:
    branches:
      - main
    paths:
      - 'recipes/**'

jobs:
  update-recipes:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Run update script
        run: python update_recipes.py

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add js/app.js
          git commit -m "Automated update of recipe list" || echo "No changes to commit"
          git push
